### PR TITLE
Editor Implementation

### PR DESCRIPTION
**Pull request by tehlordvortex**
Implemented a simple static editor to create posts.

### CODE REVIEW

**Comment by tom-ando** [comment]
Nice work, thank you so much for the help, I really appreciate it.

Just a few things to fix though, I'll open issues on your repo for you so you can fix them.

Thanks again :)

**Comment by tom-ando** [comment]
Apparently I don't know how GitHub works, so here's what doesn't work:

1. `editor.html` doesn't work. When `#submit` is pressed, nothing happens, so that'll need to be sorted out. There are two errors in the console, seemingly originating from Bootstrap.
2. Also it'd be preferable if the editor was in it's own folder, and can be opened from `editor/`, with it's js file accompanying it.
3. This last one isn't your fault, I didn't point it out (I will do it straight after this), but I would prefer if frameworks such as jQuery and Bootstrap weren't used. I'll convert everything for you if you'd like, just let me know when you're ready.

Thank you again

**Comment by tom-ando** [comment]
Also, assign yourself to issue #2

**Comment by tehlordvortex** [comment]
I used the wrong build of Popper when I was switching to the minified version, I've replaced it with the proper UMD version and will push the changes soon.
And I think you'll have to assign me to #2 yourself, I can't find any option to assign myself to it.

**Comment by tehlordvortex** [comment]
I can rewrite the editor to not depend on jQuery and Bootstrap, I'll get that done once I'm done making sure everything works properly.

Cheers.

**Comment by tom-ando** [comment]
Thank you, much appreciated.

Also I can't assign you either, I think it's because it doesn't recognise you in the repo yet.

**Comment by tehlordvortex** [comment]
I've pushed the changes to my fork. I've removed jQuery & Bootstrap. Check it out and let me know if there's anything I should change.

**Comment by tom-ando** [comment]
Works perfectly.
Thank you! :)

**Comment by tehlordvortex** [comment]
You're welcome!

**Pull request merged**
